### ISSUE TITLE
Ionic 3.4.2 - Can't bind to 'elastic-header' since it isn't a known property of 'ion-header'.

### ISSUE THREAD

**Issue by warlockdn** [pablozandona/ionic2-elastic-header#2]
Getting this error. Can you help ?

**Comment by warlockdn** [comment]
Ok that was a honest mistake. 

[elastic-header]="myContent" is in your documentation
and demo source shows 
[elasticHeader]="myContent"

**Comment by sopheamen007** [comment]
I got the same problem. anyone can help?

**Comment by sopheamen007** [comment]
oh it works. thanks @warlockdn  ;D
